studioespresso/craft-scout

- README.md
Fix link to element query docs. Master is not available any more.
> Fix link to element query docs

- composer.json
- src/models/AlgoliaIndex.php
In my multi-site setup, I found out that when saving an entry, only the last site's version of the entry will be indexed. 
i.e. Two sites (languages): English, Dutch. 
Editing the entry in English and saving will outcome with the Dutch version of the entry indexed in Algolia, as it's the last site saved on Craft.
> Added the site ID for multi sites settings.

- src/models/Settings.php
Yii 2 expects the validator to be called “integer” rather than “int”. This was causing an error when importing from a Schematic schema.yml file that included Scout plugin settings.
See: https://www.yiiframework.com/doc/guide/2.0/en/tutorial-core-validators#integer
Stack trace:
```bash
php ./craft schematic/import
Importing plugins
- Installing plugin amazon-ses
- Installing plugin aws-s3
- Installing plugin cp-field-inspect
- Installing plugin element-api
- Installing plugin redactor
- Installing plugin schematic
- Installing plugin scout
Exception 'ReflectionException' with message 'Class int does not exist'
in /srv/app/myproject/htdocs/vendor/yiisoft/yii2/di/Container.php:428
Stack trace:
#0 /srv/app/myproject/htdocs/vendor/yiisoft/yii2/di/Container.php(428): …
```
> Fix Yii validator name: “int” —> “integer”

- README.md
- src/console/controllers/IndexController.php
- src/models/AlgoliaIndex.php
Adds `scout/index/update-settings` and `scout/index/dump-settings`.
I wanted to have these settings sourced, and also needed the ability to `forwardToReplicas`, which you can't do via the Algolia admin, only the API.
> Add console commands for index settings

- src/models/AlgoliaIndex.php
If the query returns results then elements can't be deindexed
> Disabling an entry should deindex it

- CHANGELOG.md
- README.md
- src/Scout.php
- src/config.php
- src/models/Settings.php
- src/services/ScoutService.php
- src/variables/ScoutVariable.php
@Rias500 
I've implemented the Twig variables in this PR. I've also made a couple of additions, which I hope you will be OK with.
* Added a `search_api_key` setting to the model. I'm aware the plugin doesn't use this in it's operations, but from a front end perspective, it would be nice for Scout to have a setting for it, as for certain queries/operations you don't need to use the Admin key.
* Fixed up the inconsistent usage of quotes in the config example in the README.md
Please let me know if this is OK!
Many thanks!
> Add Twig variables for Algolia settings

- README.md
- src/models/AlgoliaIndex.php
You can now skip an element based on the results of its `transform`.
If you'd like to omit an element from being indexed, you can simply return an **empty array**:
```php
public function transform(Entry $entry): array
{
// Check if entry is valid for indexing
$isValid = yourCustomValidation($entry);
// If entry fails validation, return empty array
if (!$isValid) {
return [];
}
// Return normal data attributes
return [
'name' => $entry->title,
...
'lorem' => $entry->lorem,
'ipsum' => $entry->ipsum,
];
}
```
> Skip element by returning an empty array

- src/console/controllers/scout/SettingsController.php
Tiny adjustment. I was running into issues with running settings from the CLI and narrowed it down to this line.
-----
Request options must be an array or instance of `RequestOptions` to avoid a validation error.
```
[ERROR] RequestOptions can only be created from array or from RequestOptions object
InvalidArgumentException
in /project/vendor/algolia/algoliasearch-client-php/src/RequestOptions/RequestOptionsFactory.php: 50
```
> Fixed an issue with settings call

- src/engines/AlgoliaEngine.php
We're [able to set](https://github.com/riasvdv/craft-scout/blob/master/src/IndexSettings.php#L91-L93) whether we want index settings to forward to replicas or not in the index settings, but it looks like it doesn't ever actually make it to Algolia. So I've added the `forwardToReplicas` parameter to the `setSettings()` method per the [Algolia documentation](https://www.algolia.com/doc/api-reference/api-methods/set-settings/?language=php). This change has been tested on a project I'm currently working on fwiw...
> Allow index settings to be forwarded to replicas

- src/models/Settings.php
> Don't include indices in Settings::toArray() by default

- src/behaviors/SearchableBehavior.php
tl;dr This adds a check that Scout’s `sync` setting is enabled before performing the expensive queries to fetch all of an element’s relations as it’s being deleted.
***
I have a Craft site using Scout with 1,000+ very large entries (60-200 matrix blocks each, ~20,000 words of text content each, etc.). The publishing workflow of the site involves programmatically creating a new draft of each entry at different points once a year and updating that draft with content generated outside of Craft. 
_Simplified example:_
```php
$article = Entry::findOne(123);
$draft = Craft::$app->getDrafts()->createDraft($article, $currentUserId);
$newContent = MyModule::$instance->myService->getUpdatedFieldsArray();
$draft->setFieldValues($newContent);
Craft::$app->getElements()->saveElement($draft);
```
This …
> Don’t fetch relations if sync is turned off

- config/scout.php
- src/controllers/IndexController.php
- src/models/Settings.php
This adds the [ttr](https://www.yiiframework.com/extension/yiisoft/yii2-queue/doc/api/2.0/yii-queue-queue#$ttr-detail) and [priority](https://www.yiiframework.com/extension/yiisoft/yii2-queue/doc/api/2.0/yii-queue-queue#priority()-detail) queue settings to the config
> Make the queue TTR and priority configurable

- src/Scout.php
This is an extension of this commit, https://github.com/studioespresso/craft-scout/commit/8504f0d04cbedfb821e160d0db7cdc54ceabe0ed which comes from this issue, https://github.com/studioespresso/craft-scout/issues/205. The issue that this resolves is that when `maxRevisions` is set in Craft a save of one entry also triggers a delete of old revisions/elements. That can cause issues on large datasets because the `getRelatedElements` can be very costly to do during an actual request.
> Disabling relations on deletion when configured

- config/scout.php
- src/engines/Engine.php
- src/models/Settings.php
This PR is following up on https://github.com/studioespresso/craft-scout/issues/193, where I provide more context for the current limitation with splitting objects. But in short, this adds a backwards-compatible setting to opt-in for using the individual object -- not an array-wrapped object -- when there is just a single`$splittedObjects`.
The setting name is admittedly cumbersome...couldn't think of a shorter name that was as clear!
> Add support for indexing split object without array when solo (#193)

- src/IndexSettings.php
> ⚙️ Added `renderingContent` to `IndexSettings`

- src/ScoutIndex.php
- tests/unit/ScoutIndexTest.php
> feat: add lazy evaluation to criteria callable

- README.md
- src/ScoutIndex.php
- src/console/controllers/scout/IndexController.php
- src/engines/AlgoliaEngine.php
- src/templates/utility.twig
- src/utilities/ScoutUtility.php
Resolves #114 
This PR adds a flag on `ScoutIndex` to flag an index as a replica which prevents it from being sync'd by the plugin.
Replica indices can be configured by adding them to the `indices` property in config like you would a regular index with the exception of setting the flag using `->replicaIndex(true)`.
```php
[
'indices' => [
ScoutIndex::create('Products')
// ...
->indexSettings(
IndexSettings::create()->replicas(['virtual(Products_desc)'])
)
],
[
ScoutIndex::create('Products_desc')
->replicaIndex(true)
->indexSettings(IndexSettings::create()->customRanking(['desc(price)'])),
],
]
```
This roughly follows how Algolia recommends configuring replicas in code: https://www.algolia.com/doc/guides/managing-results/refine-results/sorting/how-to/sort-by-attribute/#example-relevant-sor …
> Support replica index configuration

- src/Scout.php
- src/jobs/IndexElement.php
The issue described in #266 also affects Craft 3 version of this plugin. So this PR back-ports the fix as is.
What we usually do in our own custom modules when it comes to potentially off-loading to the queue, is to always run the job. But conditionally on the queue.
So, in this case we would have done:
```
$job = new IndexElement([
'id' => $element->id,
'siteId' => $element->site->id,
]);
$queue = Craft::$app->getQueue();
if (Scout::$plugin->getSettings()->queue) {
$queue->push($job);
} else {
$job->execute($queue);
}
```
This way both paths end up doing the same work. Now if `Scout::$plugin->getSettings()->queue === false`, the extra work that the Job does does not get executed. 
I didn't think I should "pollute" this PR with that, but I could put this in a new PR if interested?
> feat: backport fix for #266 to Craft 3

- CHANGELOG.md
- src/engines/Engine.php
This fixes #259
I have not seen anything break, and orphans are now deleted as expected in the indexes I have tested manually, but I have not run any unit tests (or added any new ones), as there are no instructions on what is needed to set that up.
I can try to add unit tests if some instructions are given.
> Fixed missing deletion of orphans of split elements

- config/scout.php
- src/behaviors/SearchableBehavior.php
- src/models/Settings.php
Bringing ticket https://github.com/studioespresso/craft-scout/issues/242 is back from the dead.
--- 
I'm working on a Craft Commerce site with about ~250,000~ 650,000 SKUs.
At that scale, we hit memory limit exceeded errors for some of our Entries that have lots of relationships to Products.
Commenting out [these lines](https://github.com/studioespresso/craft-scout/blob/master/src/behaviors/SearchableBehavior.php#L150-L151) in SearchableBehavior::getRelatedElements resolved our issue.
This got me thinking... for many use cases, checking all of these Element Types is overkill. Most of our indexes only have relations between Entry and Asset elements. 
Our project still need to index relations, but by removing most Element types from that check, we improve our performance by quite a bit.
> Make `SearchableBehavior::getRelatedElements()` configurable

- composer.json
- src/ScoutIndex.php
- src/serializer/AlgoliaSerializer.php
Upgrade to most recent branch of `league/fractal`. This makes sense to do now since `craftcms/element-api` has also done this upgrade in its recent 4.x line. This should probably also be ported to the v5-develop branch, or maybe only introduce with that branche?
BREAKING CHANGE: Fractal's public API has changed in classes such as `\League\Fractal\Serializer\ArraySerializer`
> feat!: upgrade `league/fractal` to 0.20

- README.md
- src/ScoutIndex.php
- src/behaviors/SearchableBehavior.php
- src/console/controllers/scout/IndexController.php
- src/controllers/IndexController.php
- src/engines/AlgoliaEngine.php
- src/jobs/ImportIndex.php
- src/templates/utility.twig
- src/utilities/ScoutUtility.php
I came across https://github.com/studioespresso/craft-scout/issues/69#issuecomment-548764036 as I had a similar need and thought I would submit a PR for it. It closely resembles the suggested syntax [here](https://github.com/studioespresso/craft-scout/issues/69#issuecomment-616563983) but differs in that my implementation returns an array of query objects rather than merging the two. Open to any edits or feedback!
> Feature - Add support for multiple Element Types per Index

- src/ScoutIndex.php
`ScoutIndex::__construct()` was creating an element query, which is problematic because `ScoutIndex` objects are [meant to be created](https://github.com/studioespresso/craft-scout/tree/master?tab=readme-ov-file#example-index-configuration) from the plugin’s config file, which will get executed before Craft is fully initialized. (Even the `Scout` class won’t have been loaded yet at that point, let alone other plugins.) If another plugin hasn’t been loaded yet, it won’t have had a chance to register event listeners for the element query yet, etc.
In one case we are seeing this, combined with some other random plugin [also doing too much before the app is fully initialized](https://github.com/craftcms/commerce/pull/3518/files), end up causing a `Class "craft\behaviors\CustomFieldBehavior" …
> Don't create an element query right away from ScoutIndex

- src/behaviors/SearchableBehavior.php
Replica Indices will have no criteria configured.
This is intended to resolve [Issue 303](https://github.com/studioespresso/craft-scout/issues/303) for the Craft 4 compatible version of Scout.
> Ignore Replica Indices in SearchableBehavior.php

- src/Scout.php
When the `indexRelations` config is set to `false` and the queue is used, the DeindexElement queue job is not reached in the before delete element event.
This results in the element not be deindexed in Algolia.
Removing the return here ensures the queue job gets pushed.
> Fix for elements not being deindexed when indexRelations config is false and queue is enabled
